-- MySQL Script generated by MySQL Workbench
-- 01/03/17 19:34:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema questly
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `questly` ;

-- -----------------------------------------------------
-- Schema questly
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `questly` DEFAULT CHARACTER SET utf8 ;
USE `questly` ;

-- -----------------------------------------------------
-- Table `questly`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questly`.`users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `role` VARCHAR(30) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questly`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questly`.`questions` (
  `qid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NULL DEFAULT NULL,
  `votes` INT NOT NULL DEFAULT 0,
  `views` INT NOT NULL DEFAULT 0,
  `replies` INT NOT NULL DEFAULT 0,
  `title` VARCHAR(128) NOT NULL,
  `content` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`qid`),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `uid_question`
    FOREIGN KEY (`uid`)
    REFERENCES `questly`.`users` (`uid`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questly`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questly`.`answers` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NULL DEFAULT NULL,
  `qid` INT NOT NULL,
  `votes` INT NOT NULL DEFAULT 0,
  `content` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`aid`, `qid`),
  INDEX `qid_idx` (`qid` ASC),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `qid_answer`
    FOREIGN KEY (`qid`)
    REFERENCES `questly`.`questions` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uid_answer`
    FOREIGN KEY (`uid`)
    REFERENCES `questly`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questly`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questly`.`comments` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `uid` INT NULL DEFAULT NULL,
  `qid` INT NULL DEFAULT NULL,
  `aid` INT NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `aid_idx` (`aid` ASC),
  INDEX `qid_idx` (`qid` ASC),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `aid_comment`
    FOREIGN KEY (`aid`)
    REFERENCES `questly`.`answers` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `qid_comment`
    FOREIGN KEY (`qid`)
    REFERENCES `questly`.`questions` (`qid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uid_comment`
    FOREIGN KEY (`uid`)
    REFERENCES `questly`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
